services:
  expo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP}
